services:

  #Contenedor de base de datos PostgreSQL
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  #Contenedor de la aplicación Laravel
  laravel:
    image: jvl-proyecto-integrado-laravel
    container_name: laravel-app
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: mydb
      DB_USERNAME: user
      DB_PASSWORD: password
    networks:
      - app-network
    command: sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm" #Asegura permisos correctos

  #Contenedor de Nginx para servir la aplicación Laravel
  nginx:
    image: nginx:1.27
    container_name: nginx-server
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - laravel
    networks:
      - app-network

  #Contenedor de la aplicación Angular
  angular:
    image: jvl-proyecto-integrado-angular
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - laravel
    networks:
      - app-network

#Volumenes y redes utilizados por los contenedores
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
